name: UIKitDZ
options:
  deploymentTarget:
    iOS: 17.2
  bundleIdPrefix: com.UIKitDZ
  postGenCommand: pod update

packages:
  MyTextField:
    url: https://github.com/kostjkeee/MyTextField
    majorVersion: 1.1.4
  Swinject:
    url: https://github.com/Swinject/Swinject
    from: 2.8.0
  GoogleMaps:
    url: https://github.com/googlemaps/ios-maps-sdk
    majorVersion: 8.4.0

    
targets:
  UIKitDZMock:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    sources:
      - UIKitDZ
    dependencies:
      - package: MyTextField
      - package: Swinject
      - package: GoogleMaps
        product: GoogleMaps
      - package: GoogleMaps
        product: GoogleMapsBase
      - package: GoogleMaps
        product: GoogleMapsCore
    settings:
      base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "17.2"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
            OTHER_SWIFT_FLAGS: "$(inherited) -D Mock"
    preBuildScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                     export PATH="/opt/homebrew/bin:$PATH"
                fi
                if which swiftgen > /dev/null; then
                    swiftgen
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false


  UIKitDZ:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    sources:
      - UIKitDZ
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "17.2"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: MyTextField
      - package: Swinject
      - package: GoogleMaps
        product: GoogleMaps
      - package: GoogleMaps
        product: GoogleMapsBase
      - package: GoogleMaps
        product: GoogleMapsCore
    preBuildScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                     export PATH="/opt/homebrew/bin:$PATH"
                fi
                if which swiftgen > /dev/null; then
                    swiftgen
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false

  UIKitDZTests:
    type: bundle.unit-test
    platform: iOS

    deploymentTarget: "17.2"
    sources:
      - UIKitDZ
      - UIKitDZTests
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "17.2"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: MyTextField
      - package: Swinject
    preBuildScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                     export PATH="/opt/homebrew/bin:$PATH"
                fi
                if which swiftgen > /dev/null; then
                    swiftgen
                else
                    echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false     
